### ISSUE TITLE
绑定超管提示Cannot read properties of null (reading 'publicKey')

### ISSUE THREAD

**Issue by lixh00** [MirageNetwork/MirageServer#30]
如图所示，是我少了什么配置嘛？
![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/311cf7c1-3697-4d50-8c95-050257e105cd)

**Comment by gps949** [comment]
您好，出现这个提示是在点击绑定超管按钮的时候吗？使用的浏览器是什么？
绑定超管这里需要使用支持WebAuthn的硬件Key或者浏览器。目前我这边已经验证过的有yubikey、Safari、Chrome、Edge应该都可以完成。

**Comment by lixh00** [comment]
> 您好，出现这个提示是在点击绑定超管按钮的时候吗？使用的浏览器是什么？ 绑定超管这里需要使用支持WebAuthn的硬件Key或者浏览器。目前我这边已经验证过的有yubikey、Safari、Chrome、Edge应该都可以完成。

是的，我用得Chrome，是不是是因为我是在本机运行，没有绑定域名和没有https的缘故呢？

**Comment by gps949** [comment]
> > 您好，出现这个提示是在点击绑定超管按钮的时候吗？使用的浏览器是什么？ 绑定超管这里需要使用支持WebAuthn的硬件Key或者浏览器。目前我这边已经验证过的有yubikey、Safari、Chrome、Edge应该都可以完成。
> 
> 是的，我用的Chrome，是不是是因为我是在本机运行，没有绑定域名和没有https的缘故呢？

是的，为了安全性，目前WebAuthn流程里写死了使用https（是否必须域名记不清了。。。）
建议部署方式可以同时部署一个NPM（NginxProxyManager）作为前置代理为服务提供域名转发及HTTPS证书。

**Comment by lixh00** [comment]
好的，感谢解惑，我扫了一眼代码，看到硬编码写了https，但是不太确定(因为没用过WebAuthn)。

**Comment by lixh00** [comment]
老哥，我想再请教一下，在Windows11下，我用Chrome非要我插key硬件，它正常嘛？iOS我测试是能用的，我看Windows上提示说可以Windows Hello，我配置了PIN（也是Windows Hello的一种），但是不能用。
![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/40c74255-496c-4738-a4be-f480295a8902)
![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/2b0237d6-ba66-4467-b397-1ab3dbb41a28)
![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/28245e03-8485-4e4e-8c4f-d1584501c1c7)

**Comment by gps949** [comment]
> 老哥，我想再请教一下，在Windows11下，我用Chrome非要我插key硬件，它正常嘛？iOS我测试是能用的，我看Windows上提示说可以Windows Hello，我配置了PIN（也是Windows Hello的一种），但是不能用。

我看了下，Chrome目前应该只支持通过能做WebAuthn的移动设备扫码、硬件Key两种方式，这是Chrome的限制，应该是正常的。
Windows Hello我试了下是可以的。但是Windows Hello的用法是，你需要先在Windows设置中创建对应的Hello验证方式（如PIN），然后再到蜃境超管页面上进行绑定。
<img width="867" alt="截屏2023-08-31 下午2 01 58" src="https://github.com/MirageNetwork/MirageServer/assets/7601383/b509b472-2900-4cd1-8516-77c1cfdd6f4b">

**Comment by lixh00** [comment]
妥当，感谢老哥！

**Comment by lixh00** [comment]
老哥，再打扰一下，这玩意儿的客户端从哪儿来啊？

**Comment by gps949** [comment]
> 老哥，再打扰一下，这玩意儿的客户端从哪儿来啊？

可以使用Tailscale的官方客户端，也可以使用蜃境自己的客户端（目前还没系统性发布，可能比较分散）
Windows： https://github.com/MirageNetwork/.github/releases
iOS： https://testflight.apple.com/join/wg6rNFFv
其他平台不想用Tailscale想要蜃境版可以跟我说下

**Comment by lixh00** [comment]
感谢感谢~

**Comment by lixh00** [comment]
老哥老哥，我再打扰一下，那个小程序扫码登录应该怎么搞配啊？

**Comment by lixh00** [comment]
还有就是，这个东西怎么填诶？
![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/4c25bb62-5300-42fa-b457-841ff933d905)

**Comment by gps949** [comment]
> 老哥老哥，我再打扰一下，那个小程序扫码登录应该怎么配啊？

> 还有就是，这个东西怎么填诶？ ![image](https://user-images.githubusercontent.com/72033265/264888679-4c25bb62-5300-42fa-b457-841ff933d905.png)

小程序的话需要自己创建微信小程序，还是比较繁琐的，而且体验一般，已经不大建议采用这种方式了：
1、在微信公众平台创建小程序开发者账号，创建小程序
2、小程序侧代码： https://github.com/MirageNetwork/MirageTool_WXMini
3、小程序的后台服务代码：https://github.com/MirageNetwork/MirageToolServer
4、在蜃境控制器侧做相应的配置

控制器地址就填你的服务地址URL。不带https://，比如你绑定管理员时用的是```https://www.baidu.com/cockpit```这里就填```www.baidu.com```这样。

**Comment by lixh00** [comment]
控制器地址填错了怎么修改啊？我重装也没得那个提示框出来了

**Comment by gps949** [comment]
> 控制器地址填错了怎么修改啊？我重装也没得那个提示框出来了

Windows客户端吧？你在托盘图标上连续点击鼠标5次，再打开菜单会显示调试项，里面可以进行“重置服务器”

**Comment by lixh00** [comment]
好炫酷的操作，哈哈哈哈，感谢解惑

**Comment by lixh00** [comment]
老哥老哥，你能不能把你编译二进制的命令发一下啊，我搞个Dockerfile吧，我自己编译的似乎有点儿问题，启动之后页面是个大白板

**Comment by gps949** [comment]
> 老哥老哥，你能不能把你编译二进制的命令发一下啊，我搞个Dockerfile吧，我自己编译的似乎有点儿问题，启动之后页面是个大白板

完整clone 请使用
```
git clone --recurse-submodules https://github.com/MirageNetwork/MirageServer
```
在完整clone下面，运行
```
go run dist/build.go
```

**Comment by lixh00** [comment]
原来如此，我手动编译的，先npm build俩页面，然后go build server.go，看来是我姿势错了，笑死。

**Comment by lixh00** [comment]
很尬，也是白板

![image](https://github.com/MirageNetwork/MirageServer/assets/72033265/3c740d25-cf08-479b-b1c1-35199a5f2ac5)
