### ISSUE TITLE
使用Release的编译版本，提示“Server responed with error. The message is: error-创建超管凭证失败”

### ISSUE THREAD

**Issue by Kendarou** [MirageNetwork/MirageServer#31]
大佬，Debian 12上，下载了Release里的程序，直接运行。然后nginx做了反代，打开页面点绑定管理员的时候都可以弹出那个什么验证的弹窗。但是继续就会在页面右下角弹窗提示“Server responed with error. The message is: error-创建超管凭证失败”

使用了M1 Mac上的Safari，最新的Chrome，Windows 11上面的Chrome，都是一样的情况。

请教下这个是什么原因？

**Comment by gps949** [comment]
检查确认一下你反代的设置（HTTPS）（参考#30)

**Comment by gps949** [comment]
现在输出错误确实给的比较粗略，从报错信息很难判断真正的错误。
但根据你的截图，似乎你前端代理出来的端口号没采用默认https端口，指定了端口。或许是这方面的原因。

**Comment by gps949** [comment]
> 那好可惜啊，我这边有固定IP，家里也有的公网IP+DDNS域名，就是没有备案的域名，那这个是不是用不了...

目前版本仓库代码的WebAuthn是锁死不能使用非标端口的。不过应该可以加一下对自定义端口的支持，我这两天手头有些事在忙，一有时间会尽快把这个加上

**Comment by gps949** [comment]
> 那好可惜啊，我这边有固定IP，家里也有的公网IP+DDNS域名，就是没有备案的域名，那这个是不是用不了...

修改了下支持前端代理用非标端口了，你可以再试试
release二进制：
https://github.com/MirageNetwork/MirageServer/releases/tag/1.41.384-fix1

**Comment by GodRuiAn** [comment]
> > 那好可惜啊，我这边有固定IP，家里也有的公网IP+DDNS域名，就是没有备案的域名，那这个是不是用不了...
> 
> 修改了下支持前端代理用非标端口了，你可以再试试 release二进制： https://github.com/MirageNetwork/MirageServer/releases/tag/1.41.384-fix1

感谢大佬！可以正常使用了。但是搞了一下午还是不会，tailscale还是不适合我们这种小白吧。一进去什么思南什么配置的，完全不理解是什么概念...自己随便设了设也看不出什么二和三来...Google了一番也没有什么信息...还是暂时用openvpn as吧...期待大佬的项目更加完善。

**Comment by gps949** [comment]
> > > 那好可惜啊，我这边有固定IP，家里也有的公网IP+DDNS域名，就是没有备案的域名，那这个是不是用不了...
> > 
> > 
> > 修改了下支持前端代理用非标端口了，你可以再试试 release二进制： https://github.com/MirageNetwork/MirageServer/releases/tag/1.41.384-fix1
> 
> 感谢大佬！可以正常使用了。但是搞了一下午还是不会，tailscale还是不适合我们这种小白吧。一进去什么思南什么配置的，完全不理解是什么概念...自己随便设了设也看不出什么二和三来...Google了一番也没有什么信息...还是暂时用openvpn as吧...期待大佬的项目更加完善。

感谢你的尝试，是我这边的设计和开发还有很多不足。
如果有进一步的兴趣可以先使用Tailscale官方的SaaS服务进行了解： https://www.tailscale.com  
使用官方SaaS就可以省去了控制器端的配置的烦恼了，有进一步了解后也许使用起来会更上手些。   
总的来说，Tailscale比传统VPN更安全、灵活、强大、易用，不过毕竟是个新事物，确实有很多概念需要去重新了解。   

这个issue我就先关了，再有问题可以随时再提
