### ISSUE TITLE
司南如何部署？

### ISSUE THREAD

**Issue by sunflowerfa** [MirageNetwork/MirageServer#32]
如题~

**Comment by gps949** [comment]
首先，司南分为```全局司南```和```租户司南```，全局司南在```/cockpit```超管页面进行配置/部署，租户司南由租户管理员在控制台```/admin/navi```进行配置/部署。

然后，支持4种配置/部署模式：
- 配置非受管
可以直接将已有的Tailscale官方版本配置。如白嫖Tailscale[官方DERP](https://login.tailscale.com/derpmap/default)
- 自部署非受管版本
按照Tailscale[官方教程](https://tailscale.com/kb/1118/custom-derp-servers/)自行部署后，使用相关部署信息在蜃境中参照```配置非受管```的方式进行配置登记
- 自动部署受管版本
**前置条件： 需要在超管页面->设置->客户端发布上传发布司南二进制文件** 
在超管页面或管理员控制台页面上的司南页签中，点击```添加新司南```按钮，填写信息进行自动部署。
- 自部署受管版本
先在司南页面完成配置（登记），再在将运行司南的机器上执行命令行进行司南的受管启动。

**受管与非受管的区别**
受管司南会与控制器之间进行信息同步，控制器将统计司南的使用信息（如收发包之类的），司南将接收控制器提供的可信节点信息并仅为可信节点提供服务，防止被白嫖。   
非受管司南与控制器之间无信息同步（控制器仅会探测司南延迟和证书过期情况），司南是否对请求服务的节点进行校验采用与Tailscale官方DERP完全同样机制([参考这里](https://tailscale.com/kb/1118/custom-derp-servers/#optional-restricting-client-access-to-your-derp-node))   

### 下面对配置（登记）、部署在页面上需填写信息和命令行启动参数进行说明：

- 配置（登记）
参见下图，选择已有区域或创建区域
（区域的概念与Tailscale的类似，用以区分地域，比如自己业务开展地区主要在北京、上海，可以考虑创建两个区域分别添加司南）
并设置探路（STUN）端口、中继（DERP）端口值。IP为可选，要确保可用性建议配置，更注重安全性可以不配置。
<img width="506" alt="截屏2023-09-18 下午2 42 58" src="https://github.com/MirageNetwork/MirageServer/assets/7601383/293fa2cd-bcee-4da7-a0f3-147a190710fe">

- 部署
参见下图，```区域```及```端口```部分含义与配置时完全相同。
如果尚未配置域名DNS解析到司南的机器，可打开```新配DNS```，选择服务商并填写信息，会自动配置DNS解析（目前支持阿里云、腾讯云、Cloudflare、NameSilo四家服务商），需注意此时前面IP部分需要填写以供生成相应DNS解析。如果已配置好DNS此处可以关闭。
SSH地址填写将要自动部署司南的SSH地址（采用ip:port形式）。如果采用密钥需要下方公钥(全局和各个租户采用不同密钥)预先配置到待部署司南的机器上，如果采用用户名口令登录SSH则切换开关后填写用户名口令。理论上需要root用户。
<img width="496" alt="截屏2023-09-18 下午2 48 22" src="https://github.com/MirageNetwork/MirageServer/assets/7601383/897db75b-4636-4b3a-b281-1036a88d19ae">       

 - 命令行启动参数
 除支持Tailscale官方DERP的参数外，还有如下参数：
```-ctrl-url```
管控此司南的控制器URL，参数形式为"https://sdp.xxx.com" 这样
```-id```
控制器为该司南分配的注册ID，参见在司南页面添加完司南后司南列表条目下方
<img width="380" alt="截屏2023-09-18 下午3 01 05" src="https://github.com/MirageNetwork/MirageServer/assets/7601383/dc484b18-913e-408c-a49f-cf7cfd48e31c">   


P.S.
司南部署这里确实相对比较复杂，所以没有特别需求，建议采用前面说的```配置非受管```方式直接白嫖Tailscale官方的DERP节点（中国境内推荐TOK、HKG两个区域的）。
如果使用自动化远程部署，需要注意保证控制器到待部署机器间的网络条件，因为涉及二进制包（20M）的远程传输。

### 司南二进制包临时发布地址
https://github.com/MirageNetwork/MirageClient/releases/tag/navi-1.47.373

**Comment by sunflowerfa** [comment]
> 首先，司南划分`全局司南`和`租户司南`，全局司南在`/cockpit`超管页面进行配置/部署，机场司南由机场管理员在控制台`/admin/navi`进行配置/部署。
> 
> 然后，支持4种配置/部署模式：
> 
> * 配置非受管
>   可以直接将现有的 Tailscale 官方版本配置。如白嫖Tailscale[官方 DERP](https://login.tailscale.com/derpmap/default)
> * 自部署非受管版本
>   按照Tailscale[官方教程](https://tailscale.com/kb/1118/custom-derp-servers/)自行部署后，使用相关部署信息在蜃境中依托的`配置非受管`方式进行配置登记
> * 自动配置受管版本
>   **前置条件：需要在超管页面->设置->客户端发布上传发布司南二进制文件**
>   在超管页面或管理员控制台页面上的司南页签中，点击`添加新司南`按钮，填写信息进行自动部署。
> * 自部署受管版本
>   先在司南页面完成配置（登记），然后在运行司南的机器上执行命令行进行司南的受管启动。
> 
> **受管与非受管的区别** 受管司南会与控制器之间进行信息同步，控制器将统计司南的使用信息（如收发包之类的），司南将接收控制器提供的可信节点信息并非 受管司南与控制器之间无信息同步（控制器仅会探测司南延迟和证书过期情况），司南是否对请求服务的节点进行校验采用与Tailscale官方DERP完全相同的机制（[参考这里](https://tailscale.com/kb/1118/custom-derp-servers/#optional-restricting-client-access-to-your-derp-node)）
> 
> ### 下面对配置（登记）、配置页面上需填写信息和命令行启动参数进行说明：
> * 配置（登记）
>   参见下图，选择已有区域或创建区域
>   （区域的概念与尾标的类似，可以区分地域，比如自己业务开展地区主要在北京、上海，可以考虑创建两个区域分别添加司南）
>   并设置探路（STUN）端口、中继（DERP）端口值。I​​P为可选，要保证可用性建议配置，更注重安全性可以不配置。
> 
> <img alt="截屏2023-09-18 下午2 42 58" width="506" src="https://user-images.githubusercontent.com/7601383/268570983-293fa2cd-bcee-4da7-a0f3-147a190710fe.png">
> * 配置
>   见下图，`区域`及`端口`部分配置与配置时必须两个。
>   如果尚未配置DNS解析到司南的机器，可以打开`新配DNS`，选择服务商并填写信息，会自动配置DNS解析（目前支持阿里云、腾讯云、Cloudflare） 、NameSilo四家服务商），需注意此时前面的IP部分需要填写以供生成相应的DNS解析。如果已配置好DNS此处可以关闭。SSH地址填写将要自动配置司南的SSH地址（采用ip:port
>   形式）。如果采用密钥顶部全局（全局和各个配置枢纽需要不同密钥）预先到待部署司南的机器上，如果用户采用名口令登录SSH则切换开关后填写用户名口令。用户。
> 
> <img alt="截屏2023-09-18 下午2 48 22" width="496" src="https://user-images.githubusercontent.com/7601383/268571929-897db75b-4636-4b3a-b281-1036a88d19ae.png">
> * 命令行启动参数
>   除支持Tailscale官方DERP的参数外，还有以下参数：
>   `-ctrl-url`
>   管控此司南的控制器URL，参数形式为" https://sdp.xxx.com " 产品
>   `-id`
>   控制器为该司南分配的注册ID ，参见在司南页面添加完成司南后司南列表入口下方
> 
> <img alt="截屏2023-09-18 下午3 01 05" width="380" src="https://user-images.githubusercontent.com/7601383/268573962-dc484b18-913e-408c-a49f-cf7cfd48e31c.png">
> PS 司南部署这里确实相对比较复杂，所以没有特别需求，建议采用前面说的`配置非受管`方式直接白嫖Tailscale官方的DERP节点（中国境内推荐TOK、HKG两个区域的）。 如果使用自动化远程部署，需要保证注意控制器到待配置机器间的网络条件，因为涉及二进制包（20M）的远程传输。
> 
> ### 司南二进制包临时发布地址
> https://github.com/MirageNetwork/MirageClient/releases/tag/navi-1.47.373

感谢大佬回复！您有国内赞助方式么？想加一下您联系方式~
