### ISSUE TITLE
github 登录报错

### ISSUE THREAD

**Issue by gclm** [MirageNetwork/MirageServer#33]
超管页面集成github登录，然后使用 sdp 地址登录报错

![image](https://github.com/MirageNetwork/MirageServer/assets/27618687/2ec9c414-1b63-49de-90b0-449ed8b83df1)

### 错误日志如下：

```
{"level":"warn","time":"2023-09-18 16:49:49","message":"未能从Cookie读取到OIDC Token！"}
{"level":"error","caller":"/root/tmp/MirageServer/controller/oidc.go:45","error":"oidc: issuer did not match the issuer returned by provider, expected \"https://sdp.xx.club/issuer\" got \"https://vpn.xx.club/issuer\"","time":"2023-09-18 16:49:52","message":"Could not retrieve OIDC Config: oidc: issuer did not match the issuer returned by provider, expected \"https://sdp.xx.club/issuer\" got \"https://vpn.xx.club/issuer\""}
{"level":"warn","error":"oidc: issuer did not match the issuer returned by provider, expected \"https://sdp.xx.club/issuer\" got \"https://vpn.xx.club/issuer\"","time":"2023-09-18 16:49:52","message":"failed to set up OIDC provider, falling back to CLI based authentication"}
2023/09/18 16:49:52 http: panic serving 172.20.0.2:40922: runtime error: invalid memory address or nil pointer dereference
goroutine 852 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1dba4a0?, 0x362da50?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
golang.org/x/oauth2.(*Config).AuthCodeURL(0x0, {0xc0007483c0, 0x19}, {0xc00035b880, 0x2, 0x10?})
        /root/go/pkg/mod/golang.org/x/oauth2@v0.8.0/oauth2.go:153 +0x5d
MirageNetwork/MirageServer/controller.(*Mirage).doDexLogin(0xc0000d20e0, {0x25f0920, 0xc0000d3340}, 0x1f3f120?, {0xc0007483c0, 0x19}, {0xc000a6c8a9, 0x6})
        /root/tmp/MirageServer/controller/console_auth.go:103 +0x495
MirageNetwork/MirageServer/controller.(*Mirage).doLogin(0xc0000d20e0, {0x25f0920, 0xc0000d3340}, 0xc000818000)
        /root/tmp/MirageServer/controller/console_auth.go:77 +0x79d
net/http.HandlerFunc.ServeHTTP(0xc0007ddf00?, {0x25f0920?, 0xc0000d3340?}, 0x1?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000942300, {0x25f0920, 0xc0000d3340}, 0xc0007dde00)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
net/http.serverHandler.ServeHTTP({0x25ec200?}, {0x25f0920?, 0xc0000d3340?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0000a1ef0, {0x25f68b0, 0xc0009ff230})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 482
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
```

### github oauth 配置
![image](https://github.com/MirageNetwork/MirageServer/assets/27618687/3806af4b-aadf-47d6-beaa-6883a4713b08)

**Comment by gps949** [comment]
"error":"oidc: issuer did not match the issuer returned by provider, expected \"https://sdp.xx.club/issuer\" got \"https://vpn.xx.club/issuer\""

这里。看你github上配置是sdp子域的，是不是实际配置成了vpn子域的？

**Comment by gclm** [comment]
> "error":"oidc: issuer did not match the issuer returned by provider, expected "[https://sdp.xx.club/issuer\](https://sdp.xx.club/issuer%5C)" got "[https://vpn.xx.club/issuer\](https://vpn.xx.club/issuer%5C)""
> 
> 这里。看你github上配置是sdp子域的，是不是实际配置成了vpn子域的？

什么意思？

**Comment by gps949** [comment]
> > "error":"oidc: issuer did not match the issuer returned by provider, expected "[https://sdp.xx.club/issuer](https://sdp.xx.club/issuer%5C)" got "[https://vpn.xx.club/issuer](https://vpn.xx.club/issuer%5C)""
> > 这里。看你github上配置是sdp子域的，是不是实际配置成了vpn子域的？
> 
> 什么意思？

就是看你截图中github的三方认证设置的callback地址是```sdp.xx.club```的，但实际上访问的（或者超管配置页面配置的）是不是却是```vpn.xx.club```呢？

**Comment by gclm** [comment]
> > > "error":"oidc: issuer did not match the issuer returned by provider, expected "[https://sdp.xx.club/issuer](https://sdp.xx.club/issuer%5C)" got "[https://vpn.xx.club/issuer](https://vpn.xx.club/issuer%5C)""
> > > 这里。看你github上配置是sdp子域的，是不是实际配置成了vpn子域的？
> > 
> > 
> > 什么意思？
> 
> 就是看你截图中github的三方认证设置的callback地址是`sdp.xx.club`的，但实际上访问的（或者超管配置页面配置的）是不是却是`vpn.xx.club`呢？

是的。超管界面是 vpn.xx.club 代理 8081接口，sdp.xx.club 代理 8080端口

**Comment by gclm** [comment]
那接下来我如何配置比较好呢?

**Comment by sunflowerfa** [comment]
> 那接下来我如何配置比较好呢?
您可以检查一下超管页面[/cockpit#/setting/general](url)中的“设置控制器（及控制台）服务域名”是否为sdp.xx.club

**Comment by sunflowerfa** [comment]
> 那接下来我如何配置比较好呢?

您可以检查一下超管页面【设置-系统配置-基本配置】中的【设置控制器（及控制台）服务域名】是否为sdp.xx.club

**Comment by gclm** [comment]
<img width="652" alt="image" src="https://github.com/MirageNetwork/MirageServer/assets/27618687/d12356a3-2801-4fe2-90e8-1db50e3ddd6f">

**Comment by gclm** [comment]
已经检查了，是正常的。
版本：
<img width="640" alt="image" src="https://github.com/MirageNetwork/MirageServer/assets/27618687/56569711-3490-4863-a0e2-76bf38db9122">

**Comment by gclm** [comment]
问题已经找到了，控制台没有重启，重启一下控制台服务就正常了。
