### ISSUE TITLE
在codespace中编译出来二进制文件运行 然后再超管登录时候出现错误

### ISSUE THREAD

**Issue by happytrudy** [MirageNetwork/MirageServer#35]
如图：编译运行：
![image](https://github.com/MirageNetwork/MirageServer/assets/61214170/30e3a944-36d7-4913-889e-fc11bd321537)
![image](https://github.com/MirageNetwork/MirageServer/assets/61214170/9d7e3f56-b15f-4778-9ac0-97701e68716d)
上图错误如何解决？谢谢

**Comment by gps949** [comment]
参考issue #30
