### ISSUE TITLE
docker编译出来运行发现报错

### ISSUE THREAD

**Issue by happytrudy** [MirageNetwork/MirageServer#36]
docker编译工作流https://github.com/chenxudong2020/docker_builder/actions/workflows/Build_MirageServer.yml
dockerfile文件：
https://github.com/chenxudong2020/docker_builder/blob/main/MirageServer/Dockerfile
编译的docker运行脚本：
docker run --restart always -p 8081:8081 --name mirageserver -d \
registry.cn-hangzhou.aliyuncs.com/dubux/mirageserver:latest

运行查看日志docker logs mirageserver 

![image](https://github.com/MirageNetwork/MirageServer/assets/61214170/965209db-8aaf-4670-94a4-a2ad12cdc85d)

**Comment by happytrudy** [comment]
docker run --restart always -p 8081:8081 --name mirageserver --privileged=true -d \
registry.cn-hangzhou.aliyuncs.com/dubux/mirageserver:latest
找到原因了 加privileged好了

**Comment by vihor3** [comment]
可否分享一下dockerfile参考一下？
