### ISSUE TITLE
项目停更了吗？

### ISSUE THREAD

**Issue by szzylph** [MirageNetwork/MirageServer#39]
是否有计划继续更新？

**Comment by lishiren-admin** [comment]
等待更新中

**Comment by gps949** [comment]
> 是否有计划继续更新？

项目并未正式终止。
但因为该项目仅我个人在开发，近段时间来都没有时间精力可以投入进来，所以暂时并没有更新时间表。

有任何急需支持的功能点或需要修复的问题，可以在issue中提FR或Bug。

**Comment by tangxs0808** [comment]
等待进一步更新～～
